# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  #nach Aktualisierungen in Pipfile und Pipfile.lock suchen
  - package-ecosystem: "pip"
    directory: "/"
    #jeden Tag nach Aktualisierungen suchen
    schedule:
      interval: "daily"

  #nach Aktualisierungen in GitHub-Workflows suchen
  - package-ecosystem: "github-actions"
    directory: "/"
    #jeden Tag nach Aktualisierungen suchen
    schedule:
      interval: "daily"
