#Name des Workflows
name: AutoMerge

#Workflow wird gestartet bei einem Pull-Request

on:
  pull_request:

jobs:
  #Job zum automatischen Mergen von Pull-Requests von Dependabot
  auto-merge:
    #Ubuntu-Image wird verwendet
    runs-on: ubuntu-latest
    steps:
      #Repository wird ausgecheckt
      - uses: actions/checkout@v3
      #Pull-Request von Dependabot wird gemerged
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{secrets.MERGE_SECRET}}
